github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: false
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
image:
  file: .gitpod.dockerfile
tasks:
- init: >
    npm install &&
    npm install -g webpack-cli nodemon &&
    echo "############## All dependencies installed ##############" &&
    [ ! -d ./test-full-consensus ] && wget https://aschen.ovh/nimiq/test/test-full-consensus.tar
  command: [ ! -d ./test-full-consensus ] && tar -xvf test-full-consensus.tar
  command: echo "############## Starting app ##############" && npm run watch
- command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
- command: redis-server
- command: gp await-port 8080 && gp preview $(gp url 8080)
- command: [ -d ./test-full-consensus ] && npm run watch || exit
