image:
  file: .gitpod.dockerfile
tasks:
- init: >
    npm install &&
    npm install -g webpack-cli nodemon &&
    [ -d ./test-full-consensus ] && echo "Consensus already exist" || wget https://aschen.ovh/nimiq/test/test-full-consensus.tar 
    [ -d ./test-full-consensus ] || tar -xvf test-full-consensus.tar
    && npm run watch
- command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
- command: redis-server
- command: gp await-port 8080 && gp preview $(gp url 8080)
