image:
  file: .gitpod.dockerfile
tasks:
- init: >
    touch /tmp/.npm-lock &&
    npm install &&
    wget https://aschen.ovh/nimiq/test/test-full-consensus.tar && 
    tar -xvf test-full-consensus.tar &&
    rm /tmp/.npm-lock
- init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: npm run watch
- command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
- command: redis-server
- command: gp await-port 8080 && gp preview $(gp url 8080)
