language: node_js
node_js:
  - 9
  - 10
cache:
  yarn: true
services:
  - mongodb
  - redis-server
before_install:
  - mv .env.sample .env
  - sed -i 's/full/light/g' .env
  - cat .env
install:
  - npm install
  - npm run build
script:
  - node app.js &
  - sleep 30
  - echo "Run tests..."
